project:
  type: website
  output-dir: docs

website:
  title: "Edoardo Mancini"
  navbar:
    title: false
    left:
      - href: home.qmd
        text: Edoardo Mancini
      - href: vignettes/presentations_publications.qmd
        text: 📈️ Presentations and Publications
      - href: vignettes/chess.qmd
        text: ♟️ Chess
    right:
      - icon: github
        href: https://github.com/manciniedoardo
      - icon: linkedin
        href: https://www.linkedin.com/in/manciniedoardo/

format:
  html:
    theme: flatly
    css: css/styles.css
    toc: true