project:
  type: website
  output-dir: docs

website:
  title: "Edoardo Mancini"
  site-url: "https://manciniedoardo.github.io"
  favicon: images/favicon.png
  open-graph: true
  twitter-card: true
  navbar:
    title: false
    left:
      - href: index.html
        text: Edoardo Mancini
      - href: vignettes/presentations_publications.qmd
        text: 📈️ Presentations and Publications
      - href: vignettes/chess.qmd
        text: ♟️ Chess
    right:
      - icon: github
        href: https://github.com/manciniedoardo
      - icon: linkedin
        href: https://www.linkedin.com/in/manciniedoardo/
      - text: <i class='fa-brands fa-orcid'></i>
        href: https://orcid.org/0009-0006-4899-8641

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: css/style.css
    toc: true
    lightbox: true
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">